name: ci

on: [push, pull_request]
jobs:
  pylint-sanity:
    runs-on: ubuntu-latest
    container:
      image: tensorflow/tensorflow:devel
    steps:
      - name: pylint
        run: |
          /bin/bash -c "add-apt-repository ppa:deadsnakes/ppa -y && apt-get install --assume-yes python3.8 && python3.8 -m pip install pylint==2.7.4 \
          && cd /tensorflow_src && git fetch origin pull/48294/head:pylint_silence && git checkout pylint_silence && pylint -j4  ./tensorflow/"
  ci-sanity:
    runs-on: ubuntu-latest
    container:
      image: tensorflow/tensorflow:devel
    steps:
      - name: ci_santy.sh
        run: |
          /bin/bash -c "add-apt-repository ppa:deadsnakes/ppa -y && apt-get install --assume-yes python3.8 && python3.8 -m pip install pylint==2.7.4 \
          && cd /tensorflow_src && git fetch origin pull/48294/head:pylint_silence && git checkout pylint_silence && ./tensorflow/tools/ci_build/ci_sanity.sh --pylint"